server.port=8087
spring.application.name=LogPrompt

#MongoDB Configuration
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=LogPrompt

openai.api.key={OPENAI_API_KEY}
model.api.gpt.model-name=o4-mini
model.api.gpt.url=https://api.openai.com/v1/chat/completions

model.api.ollama.url=http://localhost:11434/api/generate
model.api.ollama.model-name=phi:latest