server.port=8087
spring.application.name=LogPrompt

#ai
spring.ai.ollama.chat.options.model=tinyllama:1.1b
spring.ai.openai.api-key=
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-2.0-flash

# MongoDB Configuration
spring.data.mongodb.host=192.168.2.155
spring.data.mongodb.port=27017
spring.data.mongodb.database=LogPrompt
